### ISSUE TITLE
Implement depth image filter

### ISSUE THREAD

**Issue by hk-zh** [Hongkuan-Zhou/Kinect-Fusion#2]
According to the paper, we are supposed to implement bilateral filter to the raw depth map to obtain a discontinutitu preservede depth map with less noise. 

Implement it in VirtualSensor.h

The definition of Bilateral filter can be found on wiki:
[https://en.wikipedia.org/wiki/Bilateral_filter](url)
or paper
[https://members.loria.fr/MOBerger/Enseignement/Image/Exposes/tomasiIccv98.pdf](url)

**Comment by ghost** [comment]
done, pls have a look
